import { useMemo, useState } from 'react'
import Plot from 'react-plotly.js'
export default function SphereExplorer3D(){
 const [sphere,setSphere]=useState({a:1,b:-1,c:1,r:3}); const [show,setShow]=useState({center:true,radius:true,planes:false})
 const surface=useMemo(()=>{const x=[],y=[],z=[];for(let i=0;i<=24;i++){const xr=[],yr=[],zr=[];const u=2*Math.PI*i/24;for(let j=0;j<=16;j++){const v=Math.PI*j/16;xr.push(sphere.a+sphere.r*Math.cos(u)*Math.sin(v));yr.push(sphere.b+sphere.r*Math.sin(u)*Math.sin(v));zr.push(sphere.c+sphere.r*Math.cos(v))}x.push(xr);y.push(yr);z.push(zr)}return {type:'surface',x,y,z,opacity:.65,showscale:false,colorscale:[[0,'#8fd4cc'],[1,'#0d766e']],hoverinfo:'skip'}},[sphere])
 const data=[surface]; if(show.center)data.push({type:'scatter3d',mode:'markers+text',x:[sphere.a],y:[sphere.b],z:[sphere.c],marker:{size:7,color:'#c1493f'},text:['C'],textposition:'top center',showlegend:false});if(show.radius)data.push({type:'scatter3d',mode:'lines+text',x:[sphere.a,sphere.a+sphere.r],y:[sphere.b,sphere.b],z:[sphere.c,sphere.c],line:{width:7,color:'#d99a3b'},text:['','r'],showlegend:false});if(show.planes)data.push({type:'surface',x:[-6,6],y:[-6,6],z:[[0,0],[0,0]],opacity:.15,showscale:false,colorscale:[[0,'#6177a3'],[1,'#6177a3']],hoverinfo:'skip'})
 return <div className="sphere-lab"><div className="plot-wrap"><Plot data={data} layout={{autosize:true,margin:{l:0,r:0,t:0,b:0},paper_bgcolor:'#fffdf8',scene:{aspectmode:'cube',camera:{eye:{x:1.4,y:1.4,z:1.1}},xaxis:{range:[-7,7]},yaxis:{range:[-7,7]},zaxis:{range:[-7,7]}}}} config={{responsive:true,displaylogo:false,scrollZoom:true}} useResizeHandler style={{width:'100%',height:'100%'}}/></div><div className="sphere-controls"><div>{['a','b','c','r'].map(key=><label key={key}>{key}<output>{sphere[key]}</output><input type="range" min={key==='r'?1:-4} max={key==='r'?5:4} value={sphere[key]} onChange={e=>setSphere({...sphere,[key]:Number(e.target.value)})}/></label>)}</div><div className="toggle-list">{Object.keys(show).map(key=><label key={key}><input type="checkbox" checked={show[key]} onChange={e=>setShow({...show,[key]:e.target.checked})}/> Show {key}</label>)}</div></div></div>
}

