import { useMemo, useState } from 'react'
import usePersistentState from '../hooks/usePersistentState'
import { detailedQuestions, milestones, projectChapters, projectFormats, projectRequirements, rubricCategories } from './data/projectConfig'
import { createPeerAssignments, fileMetadata, generateProjectCode, validateReview } from './services/projectService'
import './styles/project.css'

const emptySubmission = { course:'calc2', chapter:'', title:'', format:'powerpoint', description:'', deployedUrl:'', references:'', files:[], versions:[], status:'not-started', projectCode:'' }
const emptyReview = () => ({ scores:{}, justifications:{}, answers:{}, recommendedGrade:'', gradeJustification:'', status:'not-started', moderated:false, released:false })

function ProjectOverview({ project, onBegin, onReview, onInstructor }) {
  return <><header className="project-hero"><p>Semester Calculus Project</p><h1>Teach one chapter with clarity and mathematical depth.</h1><span>The central standard: could another student learn the chapter from your project?</span><div><button className="project-primary" onClick={onBegin}>{project.chapter ? 'Continue My Project' : 'Choose a Chapter'}</button><button onClick={onReview}>Peer Reviews</button><button onClick={onInstructor}>Instructor Dashboard</button></div></header>
    <div className="project-overview-grid"><section><p className="project-label">Purpose</p><h2>Build understanding, not a chapter summary.</h2><p>Your presentation or application should connect definitions, reasoning, examples, visuals, applications, practice, and solutions into a coherent teaching experience.</p></section><section><p className="project-label">Project status</p><dl><div><dt>Selected chapter</dt><dd>{project.chapter || 'Not selected'}</dd></div><div><dt>Project code</dt><dd>{project.projectCode || 'Generated after submission'}</dd></div><div><dt>Status</dt><dd>{project.status.replaceAll('-', ' ')}</dd></div></dl></section></div>
    <section className="project-section"><header><p className="project-label">Required content</p><h2>Use what fits your chapter.</h2></header><div className="requirement-grid">{projectRequirements.map((item) => <div key={item}>✓ {item}</div>)}</div></section>
    <section className="project-section"><header><p className="project-label">Milestones</p><h2>From proposal to peer review</h2></header><ol className="milestone-list">{milestones.map((item,index) => <li key={item}><span>{String(index+1).padStart(2,'0')}</span>{item}<small>Due date set by instructor</small></li>)}</ol></section>
    <section className="project-section"><header><p className="project-label">Rubric</p><h2>Instructor grading framework</h2></header><div className="rubric-summary">{rubricCategories.map((category) => <div key={category.id}><strong>{category.weight}%</strong><span>{category.label}</span></div>)}</div></section>
    <section className="blackboard-notice"><p className="project-label">Blackboard Peer Review</p><h2>The Blackboard activity remains a separate requirement.</h2><ol><li>Open your assigned anonymous project here.</li><li>Evaluate it using the complete rubric.</li><li>Write detailed, evidence-based feedback.</li><li>Choose and justify a recommended grade.</li><li>Save or submit the app review where enabled.</li><li>Complete the corresponding Blackboard activity according to your instructor’s directions.</li></ol><p>Completing this app review does not claim or verify Blackboard submission.</p></section>
  </>
}

function SubmissionWorkspace({ project, setProject, onDone }) {
  const [confirmation, setConfirmation] = useState(false)
  const submit = (event) => { event.preventDefault(); const code = project.projectCode || generateProjectCode(project.course); const submittedAt = new Date().toISOString(); const version = { id: Date.now(), number: project.versions.length + 1, submittedAt, format:project.format, files:project.files, final:true }; setProject((current) => ({...current,projectCode:code,status:'final-submitted',submittedAt,versions:[...current.versions.map((v)=>({...v,final:false})),version]})); setConfirmation(true) }
  if (confirmation) return <section className="submission-confirmation"><span>✓</span><p>Project submitted</p><h2>{project.projectCode || 'Anonymous code generated'}</h2><dl><div><dt>Chapter</dt><dd>{project.chapter}</dd></div><div><dt>Submitted</dt><dd>{new Date().toLocaleString()}</dd></div><div><dt>Peer-review status</dt><dd>Not yet assigned</dd></div></dl><button className="project-primary" onClick={onDone}>Return to Project Home</button></section>
  return <form className="submission-workspace" onSubmit={submit}><header><p className="project-label">My Project</p><h1>Plan and submit your teaching project.</h1><p>Submission files are stored as metadata in this local prototype; arbitrary student code is never executed.</p></header>
    <div className="project-form-grid"><label>Course<select value={project.course} onChange={(e)=>setProject({...project,course:e.target.value,chapter:''})}><option value="calc2">MATH 243 · Calculus II</option><option value="calc3">MATH 344 · Calculus III</option></select></label><label>Selected chapter<select required value={project.chapter} onChange={(e)=>setProject({...project,chapter:e.target.value,status:'chapter-selected'})}><option value="">Choose one chapter</option>{projectChapters[project.course].map((chapter)=><option key={chapter}>{chapter}</option>)}</select></label><label>Project title<input required value={project.title} onChange={(e)=>setProject({...project,title:e.target.value})}/></label><label>Project format<select value={project.format} onChange={(e)=>setProject({...project,format:e.target.value})}>{projectFormats.map((format)=><option value={format.id} key={format.id}>{format.label}</option>)}</select></label></div>
    <label>Short project description<textarea required minLength="50" value={project.description} onChange={(e)=>setProject({...project,description:e.target.value})} placeholder="Explain how your project will teach the chapter."/></label><div className="security-callout"><strong>Before zipping a code project</strong><p>Remove node_modules, dist, build caches, .env files, API keys, passwords, tokens, and private credentials. Include src, needed public assets, package files, a README, and useful screenshots.</p></div>
    <label>Main submission and supporting files<input type="file" multiple accept=".ppt,.pptx,.pdf,.zip,.html,.css,.js,.jsx,.json,.png,.jpg,.jpeg" onChange={(e)=>{const code=project.projectCode||'PENDING-CODE';setProject({...project,files:fileMetadata(e.target.files,code)})}}/><small>Maximum configured prototype size: 100 MB per file. Files are treated as untrusted and are not executed.</small></label>{project.files.length>0&&<ul className="file-list">{project.files.map((file)=><li key={file.originalName}><span>{file.originalName}</span><small>Reviewer display: {file.reviewerName}</small></li>)}</ul>}
    <label>Optional deployed website or video URL<input type="url" value={project.deployedUrl} onChange={(e)=>setProject({...project,deployedUrl:e.target.value})}/></label><label>References and sources<textarea required value={project.references} onChange={(e)=>setProject({...project,references:e.target.value})}/></label>{project.versions.length>0&&<section><h3>Submission versions</h3>{project.versions.map((version)=><p key={version.id}>Version {version.number} · {new Date(version.submittedAt).toLocaleString()} {version.final?'· Final':''}</p>)}</section>}<button className="project-primary" type="submit">Submit Project</button>
  </form>
}

function PeerReview({ assignment, review, setReview, onBack }) {
  const validation = validateReview(review,rubricCategories,detailedQuestions)
  const save = (status) => setReview({...review,status})
  return <div className="review-workspace"><section className="anonymous-project"><p className="project-label">Anonymous project</p><h1>Project {assignment.projectCode}</h1><p>{assignment.chapter}</p><div className="safe-preview"><strong>Untrusted submission preview</strong><p>PDFs and images may be previewed safely in a future backend-backed version. Source projects are available only as protected downloads and are never executed here.</p><button>View submission details</button></div><div className="feedback-standard"><strong>Professional feedback</strong><p>Be specific, constructive, mathematically focused, respectful, and evidence-based. Critique the work—not the person.</p></div></section><form className="peer-rubric" onSubmit={(e)=>{e.preventDefault();if(validation.complete)save('submitted')}}><button type="button" onClick={onBack}>← Peer Reviews</button><p className="project-label">Peer-review rubric</p><h2>Can this project teach the chapter?</h2>{rubricCategories.map((category)=><fieldset key={category.id}><legend>{category.label} · {category.weight}%</legend><label>Score<select required value={review.scores[category.id]||''} onChange={(e)=>setReview({...review,scores:{...review.scores,[category.id]:e.target.value}})}><option value="">Select</option>{[1,2,3,4,5].map((score)=><option key={score}>{score}</option>)}</select></label><label>Why did you give this score?<textarea required minLength="20" value={review.justifications[category.id]||''} onChange={(e)=>setReview({...review,justifications:{...review.justifications,[category.id]:e.target.value}})} placeholder="What was done well, what needs improvement, and what specific evidence supports this score?"/></label></fieldset>)}{detailedQuestions.map((question,index)=><label key={question}>{index+1}. {question}<textarea required minLength="30" value={review.answers[index]||''} onChange={(e)=>setReview({...review,answers:{...review.answers,[index]:e.target.value}})}/></label>)}<label>Recommended grade (0–100)<input type="number" min="0" max="100" required value={review.recommendedGrade} onChange={(e)=>setReview({...review,recommendedGrade:e.target.value})}/></label><label>Detailed grade justification<textarea required minLength="50" value={review.gradeJustification} onChange={(e)=>setReview({...review,gradeJustification:e.target.value})}/></label><div className="review-actions"><button type="button" onClick={()=>save('draft')}>Save Draft</button><button className="project-primary" disabled={!validation.complete}>Submit Final Review</button></div>{!validation.complete&&<p className="validation-note">Complete every score, substantive explanation, detailed response, and grade justification before final submission.</p>}</form></div>
}

function PeerAssignments({ assignments, reviews, onOpen }) { return <section className="project-section peer-list"><header><p className="project-label">Peer Reviews</p><h1>Two anonymous projects are assigned.</h1><p>Project owners and reviewer identities remain private from classmates.</p></header>{assignments.map((assignment)=><article key={assignment.id}><div><span>{assignment.id.replace('-',' ')}</span><h2>Project {assignment.projectCode}</h2><p>{assignment.chapter}</p></div><dl><div><dt>App review</dt><dd>{reviews[assignment.id]?.status||'Not started'}</dd></div><div><dt>Blackboard requirement</dt><dd>Not verified</dd></div></dl><button className="project-primary" onClick={()=>onOpen(assignment)}>{reviews[assignment.id]?.status==='draft'?'Continue Review':'Start Review'}</button></article>)}</section> }

function InstructorDashboard({ project, assignments, reviews }) { const [selected,setSelected]=useState(null); return <section className="instructor-project-dashboard"><header><p className="project-label">Private instructor view</p><h1>Project identity and moderation</h1><p>This is the only project view that connects student identity to the anonymous code.</p></header><div className="identity-table"><div className="table-head"><span>Student</span><span>Project Code</span><span>Course</span><span>Chapter</span><span>Status</span><span>Final Grade</span></div><div><span>Prototype Student</span><strong>{project.projectCode||'Not generated'}</strong><span>{project.course==='calc3'?'MATH 344':'MATH 243'}</span><span>{project.chapter||'Not selected'}</span><span>{project.status}</span><span>Not released</span></div></div><h2>Reviewer accountability</h2>{assignments.map((assignment)=><article className="moderation-card" key={assignment.id}><div><strong>Prototype Reviewer {assignment.id.endsWith('1')?'A':'B'}</strong><span>Assigned: {assignment.projectCode}</span><span>Status: {reviews[assignment.id]?.status||'not started'}</span></div><button onClick={()=>setSelected(selected===assignment.id?null:assignment.id)}>Read / Moderate Review</button>{selected===assignment.id&&<div className="moderation-panel"><p>Recommended grade: {reviews[assignment.id]?.recommendedGrade||'Not entered'}</p><p>{reviews[assignment.id]?.gradeJustification||'No feedback submitted.'}</p><div><button>Return to Student</button><button>Hide Review</button><button>Flag Feedback</button><button className="project-primary">Release Feedback</button></div></div>}</article>)}<section className="blackboard-notice"><h2>Blackboard support</h2><p>Review results can be copied or exported in a later phase. No automatic Blackboard connection is configured.</p></section></section> }

export default function StudentProjectSystem({ onHome }) {
  const [project,setProject]=usePersistentState('interactive-calculus:project',emptySubmission,{version:1})
  const assignments=useMemo(()=>createPeerAssignments(project.chapter),[project.chapter])
  const [reviews,setReviews]=usePersistentState('interactive-calculus:project-reviews',{'review-1':emptyReview(),'review-2':emptyReview()},{version:1})
  const [view,setView]=useState('home'); const [activeAssignment,setActiveAssignment]=useState(null)
  const setReview=(review)=>setReviews((current)=>({...current,[activeAssignment.id]:review}))
  return <div className="student-project-system"><nav className="project-nav"><button onClick={onHome}>← Home</button><button onClick={()=>setView('home')}>Project Home</button><button onClick={()=>setView('submission')}>My Project</button><button onClick={()=>setView('peers')}>Peer Review</button></nav>{view==='home'&&<ProjectOverview project={project} onBegin={()=>setView('submission')} onReview={()=>setView('peers')} onInstructor={()=>setView('instructor')}/>} {view==='submission'&&<SubmissionWorkspace project={project} setProject={setProject} onDone={()=>setView('home')}/>} {view==='peers'&&<PeerAssignments assignments={assignments} reviews={reviews} onOpen={(assignment)=>{setActiveAssignment(assignment);setView('review')}}/>} {view==='review'&&activeAssignment&&<PeerReview assignment={activeAssignment} review={reviews[activeAssignment.id]} setReview={setReview} onBack={()=>setView('peers')}/>} {view==='instructor'&&<InstructorDashboard project={project} assignments={assignments} reviews={reviews}/>}</div>
}
