import { useState } from 'react'
import { MathDisplay } from '../../components/MathDisplay'
import { advancedTrigLessons,advancedTrigOrder } from '../../data/advancedTrigLessons'
import '../../styles/advanced-trig-lessons.css'

const labels=['See','Understand','Formalize','Practice','Correct Mistakes','Master']
const plot=(fn)=>Array.from({length:161},(_,i)=>{const x=-Math.PI*2+Math.PI*4*i/160,y=Math.max(-4,Math.min(4,fn(x)));return`${i?'L':'M'}${30+540*i/160},${130-y*24}`}).join(' ')
function Explorer({lessonId,stage}){const [theta,setTheta]=useState(Math.PI/4),[mode,setMode]=useState('base'),[A,setA]=useState(1),[B,setB]=useState(1),[C,setC]=useState(0),[D,setD]=useState(0);const cx=150+90*Math.cos(theta),cy=120-90*Math.sin(theta)
  if(lessonId==='transformations')return <div className="atl-explorer"><svg viewBox="0 0 600 260"><path className="atl-axis" d="M30 130H570M300 15V245"/><path className="atl-main" d={plot(x=>A*Math.sin(B*(x-C))+D)}/></svg><div className="atl-sliders">{[['A',A,setA,-3,3],['B',B,setB,.25,3],['C',C,setC,-3.14,3.14],['D',D,setD,-2,2]].map(([name,value,set,min,max])=><label key={name}>{name}={Number(value).toFixed(2)}<input type="range" min={min} max={max} step=".05" value={value} onChange={e=>set(Number(e.target.value))}/></label>)}</div></div>
  if(lessonId==='graphs'||lessonId==='periodicity'||lessonId==='symmetry'||lessonId==='pythagorean-identities'||lessonId==='angle-identities')return <div className="atl-explorer atl-circle-wave"><svg viewBox="0 0 600 260"><circle className="atl-guide" cx="150" cy="120" r="90"/><path className="atl-axis" d="M45 120H255M150 15V225M300 130H580"/><path className="atl-radius" d={`M150 120L${cx} ${cy}L${cx} 120Z`}/><circle className="atl-point" cx={cx} cy={cy} r="7"/><path className="atl-main" d={plot(x=>lessonId==='graphs'&&mode==='cos'?Math.cos(x):Math.sin(x))}/></svg><label>θ={(theta/Math.PI).toFixed(2)}π<input type="range" min={-Math.PI*2} max={Math.PI*4} step=".01" value={theta} onChange={e=>setTheta(Number(e.target.value))}/></label><div><button className={mode==='base'?'active':''} onClick={()=>setMode('base')}>{stage===1?'Base identity':'Sine'}</button><button className={mode==='cos'?'active':''} onClick={()=>setMode('cos')}>{stage===1?'Divide by cos²':'Cosine'}</button><button className={mode==='sin'?'active':''} onClick={()=>setMode('sin')}>{stage===1?'Divide by sin²':'Reflect / repeat'}</button></div></div>
  if(lessonId==='combined-sinusoid')return <div className="atl-explorer"><svg viewBox="0 0 600 260"><path className="atl-axis" d="M30 130H570"/><path className="atl-wave-one" d={plot(x=>3*Math.sin(x))}/><path className="atl-wave-two" d={plot(x=>4*Math.cos(x))}/><path className="atl-main" d={plot(x=>3*Math.sin(x)+4*Math.cos(x))}/></svg><p>Blue + gold = combined teal wave · amplitude 5</p></div>
  if(lessonId==='inverse-trig')return <div className="atl-explorer"><svg viewBox="0 0 600 260"><path className="atl-axis" d="M30 130H570M300 15V245"/><path className="atl-diagonal" d="M180 245L420 15"/><path className="atl-main" d={plot(Math.sin)}/></svg><div><button onClick={()=>setMode('sin')}>sin / arcsin</button><button onClick={()=>setMode('cos')}>cos / arccos</button><button onClick={()=>setMode('tan')}>tan / arctan</button></div><p>Restrict first; then reflect across y=x. Selected: {mode}</p></div>
  return <div className="atl-explorer"><svg viewBox="0 0 600 260"><circle className="atl-guide" cx="150" cy="130" r="82"/><path className="atl-hyperbola" d="M350 25C280 70 280 190 350 235M450 25C520 70 520 190 450 235"/><path className="atl-axis" d="M45 130H555M150 35V225M400 35V225"/></svg><input type="range" min="-3" max="3" step=".05" value={theta} onChange={e=>setTheta(Number(e.target.value))}/><p>sinh({theta.toFixed(2)})={Math.sinh(theta).toFixed(3)} · cosh({theta.toFixed(2)})={Math.cosh(theta).toFixed(3)}</p></div>}

export default function AdvancedTrigLesson({lessonId,completed={},onCompletedChange,onOverview,onHome,onPrevious,onNext}){const lesson=advancedTrigLessons[lessonId]||advancedTrigLessons['pythagorean-identities'],[active,setActive]=useState(0),[choice,setChoice]=useState(null),[feedback,setFeedback]=useState('');const current=lesson.stages[active];const check=()=>{if(!current.options)return;const correct=choice===current.correct;setFeedback(correct?`Correct. ${current.keyIdea||'Keep the governing relationship visible.'}`:`Try again. Revisit the mathematical relationship before choosing.`);if(correct)onCompletedChange?.({...completed,[`${lessonId}-${active}`]:true})};const position=advancedTrigOrder.indexOf(lessonId)
  return <div className="advanced-trig-page"><nav><button onClick={onOverview}>← Trigonometry</button><button onClick={onHome}>Home</button></nav><header><p>Interactive Trigonometry · Card {lesson.number}</p><h1>{lesson.title}</h1><span>See → Understand → Formalize → Practice → Correct Mistakes → Master</span></header><ol className="atl-stage-nav">{labels.map((label,index)=><li key={label}><button className={active===index?'active':''} onClick={()=>{setActive(index);setChoice(null);setFeedback('')}}><span>0{index+1}</span>{label}{completed[`${lessonId}-${index}`]&&<b>✓</b>}</button></li>)}</ol><main><section className="atl-stage-copy"><p className="card-label">0{active+1} · {labels[active]}</p><h2>{current.title}</h2><p>{current.body}</p>{current.math&&<MathDisplay>{current.math}</MathDisplay>}{current.options&&<div className="atl-check"><h3>{current.question}</h3>{current.options.map((option,index)=><label key={option}><input type="radio" name="answer" checked={choice===index} onChange={()=>setChoice(index)}/>{option}</label>)}<button onClick={check} disabled={choice===null}>Check reasoning</button>{feedback&&<p role="status">{feedback}</p>}</div>}</section><section className="atl-stage-visual"><Explorer lessonId={lessonId} stage={active}/></section></main><nav className="atl-bottom-nav"><button onClick={onPrevious} disabled={position===0}>← Previous lesson</button><button onClick={onOverview}>All trigonometry cards</button><button onClick={onNext} disabled={position===advancedTrigOrder.length-1}>Next lesson →</button></nav></div>}
