export const componentPalette = [
  {key:'additionAnimation',label:'Current Addition Animation',group:'Current animations'},
  {key:'numberSystemExplorer',label:'Current Number System Animation',group:'Current animations'},
  {key:'naturalAddition',label:'Natural Number Addition',group:'Activities'},
  {key:'integerSubtraction',label:'Integer / Subtraction Activity',group:'Activities'},
  {key:'rationalReciprocal',label:'Rational Reciprocal Activity',group:'Activities'},
  {key:'realNumberLine',label:'Real Number Line',group:'Activities'},
  {key:'fieldTester',label:'Field Tester',group:'Activities'},
  {key:'angleExplorer',label:'Angle & Radian Explorer',group:'Trigonometry'},
  {key:'unitCircleExplorer',label:'Interactive Unit Circle',group:'Trigonometry'},
  {key:'exactValuePractice',label:'Exact Value Practice',group:'Trigonometry'},
  {key:'inverseTrigExplorer',label:'Inverse Trig Explorer',group:'Trigonometry'},
  {key:'trigFunctionLookupExplorer',label:'Trig Function Lookup',group:'Trigonometry'},
  {key:'inverseTrigBenchmarkExplorer',label:'Inverse Trig Benchmarks',group:'Trigonometry'},
  {key:'sixTrigInverseMaster',label:'6-Trig & Inverse Master',group:'Trigonometry'},
  {key:'hyperbolicExplorer',label:'Hyperbolic Explorer',group:'Trigonometry'},
  {key:'geometry:spherical-triangle',label:'Spherical Triangle',group:'Geometry'},
  {key:'geometry:primitives',label:'Point / Line / Segment / Ray',group:'Geometry'},
  {key:'geometry:rotating-angle',label:'Rotating Angle',group:'Geometry'},
  {key:'geometry:line-relationships',label:'Parallel / Perpendicular Lines',group:'Geometry'},
  {key:'geometry:distance-midpoint',label:'Distance & Midpoint',group:'Geometry'},
  {key:'geometry:triangle',label:'Triangle Explorer',group:'Geometry'},
  {key:'geometry:circle',label:'Circle Explorer',group:'Geometry'},
  {key:'geometry:slope',label:'Slope Explorer',group:'Geometry'},
  {key:'geometry:coordinate-pythagorean',label:'Coordinate Pythagorean Explorer',group:'Geometry'},
]
