import { useRef } from 'react'

const field=(label,value,onChange,type='number',props={})=><label>{label}<input type={type} value={value??''} onChange={(event)=>onChange(type==='number'?Number(event.target.value):event.target.value)} {...props}/></label>
const check=(label,value,onChange)=><label><input type="checkbox" checked={value} onChange={(event)=>onChange(event.target.checked)}/>{label}</label>

function RichContentEditor({element,onUpdate}){
  const ref=useRef(null)
  const wrap=(before,after=before)=>{const input=ref.current,start=input.selectionStart,end=input.selectionEnd,value=input.value,next=`${value.slice(0,start)}${before}${value.slice(start,end)}${after}${value.slice(end)}`;onUpdate({content:next});requestAnimationFrame(()=>{input.focus();input.setSelectionRange(start+before.length,end+before.length)})}
  return <div className="rich-content-editor"><label>{element.type==='math'?'Markdown + LaTeX':'Content'}<textarea ref={ref} value={element.content||''} onChange={(event)=>onUpdate({content:event.target.value})}/></label><div className="rich-selection-tools"><button type="button" onClick={()=>wrap('**')}>Bold</button><button type="button" onClick={()=>wrap('*')}>Italic</button><label>Size<input type="number" min="8" max="96" defaultValue="22" onChange={(event)=>event.target.value&&wrap(`<span style="font-size:${event.target.value}px">`,'</span>')}/></label><label>Text<input type="color" defaultValue="#102a36" onChange={(event)=>wrap(`<span style="color:${event.target.value}">`,'</span>')}/></label><label>Highlight<input type="color" defaultValue="#fff1a8" onChange={(event)=>wrap(`<mark style="background-color:${event.target.value}">`,'</mark>')}/></label></div><small>Select text first; formatting is stored as portable Markdown or safe inline styling.</small></div>
}

function QuestionSettings({element,onUpdate}){
  const q=element.question||{},update=(change)=>onUpdate({question:{...q,...change}})
  return <div className="question-settings"><h4>Live question</h4><label>Question type<select value={q.type||'multiple-choice'} onChange={(e)=>update({type:e.target.value})}>{['multiple-choice','multiple-select','true-false','numerical','mathematical-expression','short-answer','confidence','conceptual'].map((type)=><option value={type} key={type}>{type}</option>)}</select></label><label>Prompt<textarea value={q.prompt||''} onChange={(e)=>update({prompt:e.target.value})}/></label>{['multiple-choice','multiple-select','true-false'].includes(q.type)&&<label>Answer choices<textarea value={(q.options||[]).join('\n')} onChange={(e)=>update({options:e.target.value.split('\n')})}/></label>}{field('Correct answer',q.correctAnswer,(correctAnswer)=>update({correctAnswer}),'text')}{field('Topic',q.topic||'General',(topic)=>update({topic}),'text')}<label>Difficulty<select value={q.difficulty||'medium'} onChange={(e)=>update({difficulty:e.target.value})}><option>easy</option><option>medium</option><option>hard</option></select></label>{field('Attempts',q.attempts||1,(attempts)=>update({attempts}))}{field('Timer seconds',q.timer||'',(timer)=>update({timer:timer||null}))}<label>Explanation<textarea value={q.explanation||''} onChange={(e)=>update({explanation:e.target.value})}/></label>{check('Immediate feedback',!!q.immediateFeedback,(immediateFeedback)=>update({immediateFeedback}))}{check('Confidence follow-up',!!q.confidenceFollowUp,(confidenceFollowUp)=>update({confidenceFollowUp}))}</div>
}

export default function ElementInspector({elements,onUpdate,onAlign,onDuplicate,onDelete,onLayer}){
  const element=elements[0]
  if(!element)return <section className="element-inspector"><p>Select an element to edit its position, size, style, layer, and reveal behavior.</p></section>
  const mixed=elements.length>1,textual=['text','heading','bullets','block','math','combined','definition'].includes(element.type)
  return <section className="element-inspector"><header><span>{mixed?`${elements.length} elements`:element.type}</span><h3>{mixed?'Multiple selection':element.content?.split('\n')[0]||element.question?.prompt||element.component}</h3></header>{!mixed&&<>{textual&&<RichContentEditor element={element} onUpdate={onUpdate}/>}<div className="inspector-grid">{field('X %',element.x,(x)=>onUpdate({x}))}{field('Y %',element.y,(y)=>onUpdate({y}))}{field('Width %',element.width,(width)=>onUpdate({width}))}{field('Height %',element.height,(height)=>onUpdate({height}))}</div>{textual&&<><div className="inspector-grid">{field('Block font size',element.fontSize,(fontSize)=>onUpdate({fontSize}))}{field('Block text color',element.color||'#102a36',(color)=>onUpdate({color}),'color')}{field('Block highlight',element.background||'#ffffff',(background)=>onUpdate({background}),'color')}</div><div className="format-buttons"><button className={element.fontWeight>=700?'active':''} onClick={()=>onUpdate({fontWeight:element.fontWeight>=700?400:700})}>Bold block</button>{['left','center','right'].map((align)=><button className={element.align===align?'active':''} onClick={()=>onUpdate({align})} key={align}>{align}</button>)}</div>{check('Fit box height to content',element.autoSize!==false,(autoSize)=>onUpdate({autoSize}))}</>}{field('Reveal step',element.revealStep||0,(revealStep)=>onUpdate({revealStep}))}<button onClick={()=>onUpdate({locked:!element.locked})}>{element.locked?'Unlock':'Lock'} element</button>{element.type==='interactive'&&<div className="activity-settings"><h4>Activity settings</h4>{field('Minimum',element.settings?.min??1,(min)=>onUpdate({settings:{...element.settings,min}}))}{field('Maximum',element.settings?.max??10,(max)=>onUpdate({settings:{...element.settings,max}}))}</div>}{element.type==='live-question'&&<QuestionSettings element={element} onUpdate={onUpdate}/>}<div className="visibility-settings"><h4>Visibility</h4>{check('Presentation',element.showInPresentation!==false,(showInPresentation)=>onUpdate({showInPresentation}))}{check('Student notes',element.showInStudentNotes!==false,(showInStudentNotes)=>onUpdate({showInStudentNotes}))}{check('Instructor editor',element.showInInstructorEditor!==false,(showInInstructorEditor)=>onUpdate({showInInstructorEditor}))}</div></>}<h4>Align selection</h4><div className="format-buttons">{['left','center','right','top','middle','bottom','distribute-h','distribute-v'].map((action)=><button onClick={()=>onAlign(action)} key={action}>{action}</button>)}</div><h4>Layers</h4><div className="format-buttons"><button onClick={()=>onLayer('front')}>Bring to front</button><button onClick={()=>onLayer('forward')}>Forward</button><button onClick={()=>onLayer('backward')}>Backward</button><button onClick={()=>onLayer('back')}>Send to back</button></div><div className="inspector-actions"><button onClick={onDuplicate}>Duplicate</button><button className="danger" onClick={onDelete}>Delete</button></div></section>
}
