const field=(label,value,onChange,type='number',props={})=><label>{label}<input type={type} value={value??''} onChange={(event)=>onChange(type==='number'?Number(event.target.value):event.target.value)} {...props}/></label>
const check=(label,value,onChange)=><label><input type="checkbox" checked={value} onChange={(event)=>onChange(event.target.checked)}/>{label}</label>

function QuestionSettings({element,onUpdate}){
  const q=element.question||{},update=(change)=>onUpdate({question:{...q,...change}})
  return <div className="question-settings"><h4>Live question</h4><label>Question type<select value={q.type||'multiple-choice'} onChange={(e)=>update({type:e.target.value})}>{['multiple-choice','true-false','numerical','mathematical-expression','short-answer','confidence','conceptual'].map((type)=><option value={type} key={type}>{type}</option>)}</select></label><label>Prompt<textarea value={q.prompt||''} onChange={(e)=>update({prompt:e.target.value})}/></label>{['multiple-choice','true-false'].includes(q.type)&&<label>Answer choices<textarea value={(q.options||[]).join('\n')} onChange={(e)=>update({options:e.target.value.split('\n')})}/></label>}{field('Correct answer',q.correctAnswer,(correctAnswer)=>update({correctAnswer}),'text')}{field('Topic',q.topic||'General',(topic)=>update({topic}),'text')}<label>Difficulty<select value={q.difficulty||'medium'} onChange={(e)=>update({difficulty:e.target.value})}><option>easy</option><option>medium</option><option>hard</option></select></label>{field('Attempts',q.attempts||1,(attempts)=>update({attempts}))}{field('Timer seconds',q.timer||'',(timer)=>update({timer:timer||null}))}<label>Explanation<textarea value={q.explanation||''} onChange={(e)=>update({explanation:e.target.value})}/></label>{check('Immediate feedback',!!q.immediateFeedback,(immediateFeedback)=>update({immediateFeedback}))}{check('Confidence follow-up',!!q.confidenceFollowUp,(confidenceFollowUp)=>update({confidenceFollowUp}))}</div>
}

export default function ElementInspector({elements,onUpdate,onAlign,onDuplicate,onDelete,onLayer}){
  const element=elements[0]
  if(!element)return <section className="element-inspector"><p>Select an element to edit its position, size, style, layer, and reveal behavior.</p></section>
  const mixed=elements.length>1,textual=['text','block','math'].includes(element.type)
  return <section className="element-inspector"><header><span>{mixed?`${elements.length} elements`:element.type}</span><h3>{mixed?'Multiple selection':element.content?.split('\n')[0]||element.question?.prompt||element.component}</h3></header>{!mixed&&<>{textual&&<label>Content<textarea value={element.content||''} onChange={(e)=>onUpdate({content:e.target.value})}/></label>}<div className="inspector-grid">{field('X %',element.x,(x)=>onUpdate({x}))}{field('Y %',element.y,(y)=>onUpdate({y}))}{field('Width %',element.width,(width)=>onUpdate({width}))}{field('Height %',element.height,(height)=>onUpdate({height}))}</div>{textual&&<><div className="inspector-grid">{field('Font size',element.fontSize,(fontSize)=>onUpdate({fontSize}))}{field('Text color',element.color||'#102a36',(color)=>onUpdate({color}),'color')}</div><div className="format-buttons"><button className={element.fontWeight>=700?'active':''} onClick={()=>onUpdate({fontWeight:element.fontWeight>=700?400:700})}>Bold</button>{['left','center','right'].map((align)=><button className={element.align===align?'active':''} onClick={()=>onUpdate({align})} key={align}>{align}</button>)}</div></>}{field('Reveal step',element.revealStep||0,(revealStep)=>onUpdate({revealStep}))}<button onClick={()=>onUpdate({locked:!element.locked})}>{element.locked?'Unlock':'Lock'} element</button>{element.type==='interactive'&&<div className="activity-settings"><h4>Activity settings</h4>{field('Minimum',element.settings?.min??1,(min)=>onUpdate({settings:{...element.settings,min}}))}{field('Maximum',element.settings?.max??10,(max)=>onUpdate({settings:{...element.settings,max}}))}</div>}{element.type==='live-question'&&<QuestionSettings element={element} onUpdate={onUpdate}/>}<div className="visibility-settings"><h4>Visibility</h4>{check('Presentation',element.showInPresentation!==false,(showInPresentation)=>onUpdate({showInPresentation}))}{check('Student notes',element.showInStudentNotes!==false,(showInStudentNotes)=>onUpdate({showInStudentNotes}))}{check('Instructor editor',element.showInInstructorEditor!==false,(showInInstructorEditor)=>onUpdate({showInInstructorEditor}))}</div></>}<h4>Align selection</h4><div className="format-buttons">{['left','center','right','top','middle','bottom','distribute-h','distribute-v'].map((action)=><button onClick={()=>onAlign(action)} key={action}>{action}</button>)}</div><h4>Layers</h4><div className="format-buttons"><button onClick={()=>onLayer('front')}>Bring to front</button><button onClick={()=>onLayer('forward')}>Forward</button><button onClick={()=>onLayer('backward')}>Backward</button><button onClick={()=>onLayer('back')}>Send to back</button></div><div className="inspector-actions"><button onClick={onDuplicate}>Duplicate</button><button className="danger" onClick={onDelete}>Delete</button></div></section>
}
