import { MathDisplay } from '../../components/MathDisplay'
import { getLectureSemantic } from '../services/lectureSemantics'

function ProjectedContent({items=[]}){return <div className="packet-projected-content">{items.map((item,index)=>item.kind==='math'?<MathDisplay key={index}>{item.value}</MathDisplay>:item.kind==='list'?<ul key={index}>{(item.value||[]).map(value=><li key={value}>{value}</li>)}</ul>:<p key={index}>{String(item.value||'')}</p>)}</div>}

export default function InstructorPacket({lecture,slides}){
  const print=()=>{document.body.classList.add('printing-instructor-packet');requestAnimationFrame(()=>{window.print();setTimeout(()=>document.body.classList.remove('printing-instructor-packet'),300)})}
  return <><button type="button" onClick={print}>Print Instructor Packet</button><article className="instructor-packet" aria-hidden="true"><header><p>{lecture.course} · {lecture.chapter}</p><h1>{lecture.title}</h1><strong>{slides.length} slides · private instructor copy</strong></header>{slides.map((slide,index)=>{const semantic=getLectureSemantic(slide.type);return <section className={`packet-slide packet-semantic-${semantic.kind}`} key={slide.id}><header><span>{index+1}</span><div><small>{semantic.icon} {semantic.label}</small><h2>{slide.title}</h2></div></header><ProjectedContent items={slide.presentationContent}/>{slide.question&&<div className="packet-question"><h3>Ask class</h3><p>{slide.question.prompt}</p>{slide.question.options&&<ol type="A">{slide.question.options.map(option=><li key={option}>{option}</li>)}</ol>}<strong>Answer: {slide.question.options?.[slide.question.correctAnswer]??slide.question.correctAnswer??'Review manually'}</strong>{slide.question.explanation&&<p>{slide.question.explanation}</p>}</div>}<div className="packet-notes"><h3>Private teaching sheet</h3>{slide.presenterNotes?.length?slide.presenterNotes.map((item,noteIndex)=><section className={`packet-note packet-note-${getLectureSemantic(item.type).kind}`} key={`${item.type}-${noteIndex}`}><strong>{item.title||item.type}</strong>{item.content&&<p>{item.content}</p>}{item.math&&<MathDisplay>{item.math}</MathDisplay>}</section>):<p>No private notes supplied for this slide.</p>}</div>{slide.revealSteps?.length>0&&<div className="packet-reveals"><h3>Reveal order</h3><ol>{slide.revealSteps.map(step=><li key={step}>{step}</li>)}</ol></div>}</section>})}</article></>
}
