import { useState } from 'react'
import { MathInline } from '../../components/MathDisplay'
import './inverse-trig-benchmarks.css'

const families=[
  {key:'asin',name:'Inverse Sine',symbol:'\\arcsin x',domain:'x\\in[-1,1]',range:'\\theta\\in[-\\pi/2,\\pi/2]',values:[['\\frac12','\\frac{\\pi}{6}','30^\\circ',30],['-\\frac{\\sqrt2}{2}','-\\frac{\\pi}{4}','-45^\\circ',-45],['1','\\frac{\\pi}{2}','90^\\circ',90]]},
  {key:'acos',name:'Inverse Cosine',symbol:'\\arccos x',domain:'x\\in[-1,1]',range:'\\theta\\in[0,\\pi]',values:[['\\frac{\\sqrt3}{2}','\\frac{\\pi}{6}','30^\\circ',30],['-\\frac12','\\frac{2\\pi}{3}','120^\\circ',120],['0','\\frac{\\pi}{2}','90^\\circ',90]],note:'Negative cosine belongs in Quadrant II on the arccos principal range.'},
  {key:'atan',name:'Inverse Tangent',symbol:'\\arctan x',domain:'x\\in(-\\infty,\\infty)',range:'\\theta\\in(-\\pi/2,\\pi/2)',values:[['1','\\frac{\\pi}{4}','45^\\circ',45],['-\\sqrt3','-\\frac{\\pi}{3}','-60^\\circ',-60],['0','0','0^\\circ',0]]},
]

export default function InverseTrigBenchmarkExplorer(){
  const [active,setActive]=useState('asin'),[angle,setAngle]=useState(30),family=families.find(item=>item.key===active),r=58,cx=78,cy=76,radians=angle*Math.PI/180,px=cx+r*Math.cos(radians),py=cy-r*Math.sin(radians)
  return <section className="inverse-benchmark-explorer"><header><strong>Principal-value benchmark explorer</strong><span>Choose a card, then select an exact value.</span></header><div className="inverse-benchmark-layout"><div className="inverse-benchmark-cards">{families.map(item=><article className={active===item.key?'active':''} key={item.key} onClick={()=>{setActive(item.key);setAngle(item.values[0][3])}}><button type="button" onClick={()=>{setActive(item.key);setAngle(item.values[0][3])}}><MathInline>{item.symbol}</MathInline><span>{item.name}</span></button><p><MathInline>{item.domain}</MathInline> → <MathInline>{item.range}</MathInline></p>{item.values.map(([input,output,degrees,value])=><button className="benchmark-value" type="button" onClick={(event)=>{event.stopPropagation();setActive(item.key);setAngle(value)}} key={input}><MathInline>{`${item.symbol.replace('x',`(${input})`)}=${output}`}</MathInline><small><MathInline>{degrees}</MathInline></small></button>)}{item.note&&<em>{item.note}</em>}</article>)}</div><aside className="benchmark-circle"><svg viewBox="0 0 156 152" role="img" aria-label={`Principal angle ${angle} degrees on a unit circle`}><line x1="10" x2="146" y1={cy} y2={cy}/><line x1={cx} x2={cx} y1="8" y2="144"/><circle cx={cx} cy={cy} r={r}/><line className="benchmark-radius" x1={cx} y1={cy} x2={px} y2={py}/><line className="benchmark-coordinate" x1={px} y1={py} x2={px} y2={cy}/><circle className="benchmark-point" cx={px} cy={py} r="5"/></svg><div><strong><MathInline>{family.symbol}</MathInline></strong><span>Principal angle: {angle}°</span><small><MathInline>{`(\\cos\\theta,\\sin\\theta)`}</MathInline></small><small>Only the highlighted principal range is returned by the inverse.</small></div></aside></div></section>
}
