import { useMemo } from 'react'
import { auditSlide } from '../services/slideQualityService'

const hookIds={'real-numbers':{opening:'rn-story-hook',closing:'rn-story-joke'},geometry:{opening:'geo-spherical-prediction',closing:'geo-spherical-callback'},trigonometry:{opening:'trig-circle-wave-hook'},'inverse-trigonometric-functions':{opening:'it-curiosity-hook'},'hyperbolic-functions':{opening:'hy-cable-hook'},limits:{opening:'lh-hook'}}
const malformed=/\[object Object\]|\bundefined\b|\bNaN\b|<<<<<<<|>>>>>>>/g
const suspiciousMath=[
  {pattern:/\\cosh\^?2\s*x?\s*\+\s*\\sinh\^?2\s*x?\s*=\s*1/,message:'Possible circular-sign error: the fundamental hyperbolic identity uses subtraction.'},
  {pattern:/\\sinh\s*x\s*=\s*\\frac\{e\^x\+e\^\{-x\}/,message:'Possible definition error: sinh uses a difference of exponentials.'},
  {pattern:/\\cosh\s*x\s*=\s*\\frac\{e\^x-e\^\{-x\}/,message:'Possible definition error: cosh uses a sum of exponentials.'},
]

export default function LectureQAPanel({lectureId,slides}){
  const qa=useMemo(()=>{
    const ids=hookIds[lectureId]||{},elements=slides.flatMap(slide=>slide.elements||[]),audits=slides.map(auditSlide)
    const types=new Set(slides.map(slide=>slide.type)),notes=slides.flatMap(slide=>slide.presenterNotes||[])
    const mathSources=[...elements.filter(element=>['math','combined'].includes(element.type)).map(element=>String(element.content||element.math||'')),...slides.flatMap(slide=>(slide.presentationContent||[]).filter(item=>item.kind==='math').map(item=>String(item.value||'')))]
    const allContent=[...mathSources,...elements.map(element=>String(element.content||''))].join('\n')
    const mathConcerns=[...(allContent.match(malformed)||[]).map(value=>`Malformed output: ${value}`),...suspiciousMath.filter(check=>check.pattern.test(allContent)).map(check=>check.message)]
    const belowMinimum=elements.filter(element=>element.showInPresentation!==false&&Number(element.fontSize||22)<16)
    const instructorMinimum=belowMinimum.filter(element=>element.instructorOverride)
    const noteInconsistencies=slides.filter(slide=>!(slide.presenterNotes||[]).length&&!slide.masterRequirement).map(slide=>slide.id)
    const crowded=audits.filter(audit=>audit.suggestSplit).length
    const overlaps=audits.reduce((sum,audit)=>sum+audit.issues.filter(issue=>['boundary','hidden','collision'].includes(issue.type)).length,0)
    const unresolved=mathConcerns.length+belowMinimum.length+noteInconsistencies.length+overlaps
    return {opening:!ids.opening||slides.some(slide=>slide.id===ids.opening),closing:!ids.closing||slides.some(slide=>slide.id===ids.closing),spark:slides.some(slide=>slide.masterRequirement==='spark'||slide.type==='mathematical-spark'),smile:slides.some(slide=>slide.masterRequirement==='smile'||slide.type==='mathematical-smile'),definitions:types.has('definition'),theorems:types.has('theorem')||types.has('property'),examples:[...types].some(type=>type.includes('example'))||types.has('application'),solutions:notes.some(item=>/solution/i.test(`${item.type} ${item.title}`))||slides.some(slide=>slide.solutionFor),proofs:notes.some(item=>/proof|derivation/i.test(`${item.type} ${item.title}`))||types.has('derivation'),equationsChecked:mathSources.length,graphsChecked:slides.filter(slide=>slide.visualization||elements.some(element=>element.type==='interactive'&&element.id?.startsWith(`${slide.id}-`))).length,animationsChecked:slides.filter(slide=>slide.visualization||(slide.revealSteps||[]).length).length,animationStatesChecked:slides.reduce((sum,slide)=>sum+Math.max(1,(slide.revealSteps||[]).length+1),0),questions:slides.filter(slide=>slide.question).length+elements.filter(element=>element.type==='live-question').length,mathConcerns,mathCorrected:slides.reduce((sum,slide)=>sum+(slide.qaCorrections||[]).length,0),belowMinimum,instructorMinimum,crowded,splitCompleted:slides.filter(slide=>slide.splitFrom).length,noteInconsistencies,overlaps,protectedSlides:slides.filter(slide=>slide.protectedFromAI).length,overriddenElements:elements.filter(element=>element.instructorOverride).length,unresolved}
  },[lectureId,slides])
  const pass=value=>value?'✓':'Missing'
  const approved=qa.unresolved===0
  return <details className={`lecture-qa-panel ${approved?'qa-approved':'qa-blocked'}`}><summary>Lecture QA · {approved?'Approved':'Needs attention'}</summary><div className="qa-status-grid"><span>Math Correct <b>{qa.mathConcerns.length?'Review':'✓'}</b></span><span>Readable / Accessible <b>{qa.belowMinimum.length?'Review':'✓'}</b></span><span>Presenter Notes Complete <b>{qa.noteInconsistencies.length?'Review':'✓'}</b></span><span>Unresolved Concerns <b>{qa.unresolved}</b></span></div><div><span>Slides <b>{slides.length}</b></span><span>Opening Hook <b>{pass(qa.opening)}</b></span>{hookIds[lectureId]?.closing&&<span>Closing Hook <b>{pass(qa.closing)}</b></span>}<span>Definitions <b>{pass(qa.definitions)}</b></span><span>Theorems / Properties <b>{pass(qa.theorems)}</b></span><span>Examples <b>{pass(qa.examples)}</b></span><span>Solutions <b>{pass(qa.solutions)}</b></span><span>Proofs / Derivations <b>{pass(qa.proofs)}</b></span><span>Equations Checked <b>{qa.equationsChecked}</b></span><span>Graphs Checked <b>{qa.graphsChecked}</b></span><span>Animations Checked <b>{qa.animationsChecked}</b></span><span>Animation States <b>{qa.animationStatesChecked}</b></span><span>Live Questions <b>{qa.questions}</b></span><span>Math Errors Found <b>{qa.mathConcerns.length}</b></span><span>Math Errors Corrected <b>{qa.mathCorrected}</b></span><span>Text Below 16 pt <b>{qa.belowMinimum.length}</b></span><span>Overcrowded Slides <b>{qa.crowded}</b></span><span>Slides Split <b>{qa.splitCompleted}</b></span><span>Overflow / Collision <b>{qa.overlaps}</b></span><span>Note Inconsistencies <b>{qa.noteInconsistencies.length}</b></span><span>Protected Slides <b>{qa.protectedSlides}</b></span><span>Instructor Overrides <b>{qa.overriddenElements}</b></span></div>{qa.instructorMinimum.length>0&&<p className="qa-override-warning">Accessibility warning: {qa.instructorMinimum.length} instructor-edited element(s) are below the 16 pt classroom minimum. They were not resized automatically.</p>}{qa.mathConcerns.length>0&&<ul>{qa.mathConcerns.map(concern=><li key={concern}>Possible issue detected; review without overwriting instructor content: {concern}</li>)}</ul>}{qa.noteInconsistencies.length>0&&<p>Slides missing presenter notes: {qa.noteInconsistencies.join(', ')}</p>}</details>
}
