import { useMemo, useState } from 'react'

export default function LiveQuestionLauncher({slides,session,onOpen}){
  const bank=useMemo(()=>slides.flatMap((slide)=>[...(slide.question?[{...slide.question,bankId:slide.id,label:`${slide.title} · ${slide.question.topic||'General'}`}]:[]),...(slide.elements||[]).filter((element)=>element.type==='live-question').map((element)=>({...element.question,bankId:element.id,label:`${slide.title} · ${element.question?.topic||'General'}`}))]),[slides])
  const [selected,setSelected]=useState(bank[0]?.bankId||''),[quick,setQuick]=useState(false),[type,setType]=useState('multiple-choice'),[prompt,setPrompt]=useState(''),[choices,setChoices]=useState(''),[answer,setAnswer]=useState(''),[topic,setTopic]=useState('General')
  const launchBank=()=>{const question=bank.find((item)=>item.bankId===selected);if(question&&session)onOpen(session.id,question)}
  const launchQuick=()=>{if(!prompt.trim()||!session)return;const options=['multiple-choice','true-false'].includes(type)?(type==='true-false'?['True','False']:choices.split('\n').map((x)=>x.trim()).filter(Boolean)):undefined;onOpen(session.id,{type,prompt,options,correctAnswer:options?Math.max(0,options.findIndex((x)=>x===answer)):answer,topic,difficulty:'medium',attempts:1,source:'quick'});setQuick(false);setPrompt('');setChoices('');setAnswer('')}
  if(!session)return null
  return <section className="live-question-launcher"><strong>Ask Class</strong><select value={selected} onChange={(e)=>setSelected(e.target.value)}><option value="">Existing question…</option>{bank.map((q)=><option value={q.bankId} key={q.bankId}>{q.label}</option>)}</select><button onClick={launchBank} disabled={!selected}>Open Question</button><button onClick={()=>setQuick((v)=>!v)}>Quick Question</button>{quick&&<div className="quick-question-form"><label>Type<select value={type} onChange={(e)=>setType(e.target.value)}>{['multiple-choice','true-false','numerical','short-answer','confidence'].map((value)=><option value={value} key={value}>{value}</option>)}</select></label><label>Prompt<input value={prompt} onChange={(e)=>setPrompt(e.target.value)}/></label>{type==='multiple-choice'&&<label>Choices, one per line<textarea value={choices} onChange={(e)=>setChoices(e.target.value)}/></label>}<label>Correct answer<input value={answer} onChange={(e)=>setAnswer(e.target.value)}/></label><label>Topic<input value={topic} onChange={(e)=>setTopic(e.target.value)}/></label><button onClick={launchQuick}>Launch Immediately</button></div>}</section>
}
