import { MathDisplay } from '../../components/MathDisplay'

const medals=['🥇','🥈','🥉','4','5']
function RightAngleVectors(){return <svg className="quiz-right-angle-visual" viewBox="0 0 360 190" role="img" aria-label="Two perpendicular vectors meeting at a ninety degree angle"><defs><marker id="quiz-arrow-a" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#38bdf8"/></marker><marker id="quiz-arrow-b" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#f59e0b"/></marker></defs><line x1="72" y1="145" x2="300" y2="145" stroke="#38bdf8" strokeWidth="8" markerEnd="url(#quiz-arrow-a)"/><line x1="72" y1="145" x2="72" y2="25" stroke="#f59e0b" strokeWidth="8" markerEnd="url(#quiz-arrow-b)"/><path d="M72 111 H106 V145" fill="none" stroke="#fff" strokeWidth="5"/><text x="275" y="130" fill="#fff" fontSize="25" fontWeight="800">a</text><text x="91" y="42" fill="#fff" fontSize="25" fontWeight="800">b</text><text x="112" y="113" fill="#fff" fontSize="22" fontWeight="800">90°</text></svg>}
function DeterminantDiagonals(){return <svg className="quiz-right-angle-visual" viewBox="0 0 360 230" role="img" aria-label="Two by two determinant showing main diagonal ad minus other diagonal bc"><path d="M80 28H60V190H80M280 28h20v162h-20" fill="none" stroke="#fff" strokeWidth="6"/><line x1="115" y1="62" x2="245" y2="160" stroke="#38bdf8" strokeWidth="8" strokeLinecap="round"/><line x1="245" y1="62" x2="115" y2="160" stroke="#f59e0b" strokeWidth="8" strokeLinecap="round"/><g fill="#fff" fontSize="38" fontWeight="900" textAnchor="middle"><text x="115" y="72">a</text><text x="245" y="72">b</text><text x="115" y="174">c</text><text x="245" y="174">d</text></g><text x="180" y="218" fill="#fff" fontSize="24" fontWeight="800" textAnchor="middle"><tspan fill="#7dd3fc">ad</tspan><tspan> − </tspan><tspan fill="#fbbf24">bc</tspan></text></svg>}
export default function LiveQuizSequenceView({slide,session}){
  const view=slide?.liveQuizView;if(!view)return null;const question=session?.active_question
  if(view==='leaderboard'){const rows=session?.question_leaderboard||[];return <section className="live-quiz-sequence leaderboard-view" aria-live="polite"><p className="quiz-kicker">Speed leaderboard</p><h2>Fastest Correct Answers</h2>{rows.length?<ol>{rows.map((row,index)=><li className={index===0?'winner':''} key={`${row.displayName}-${row.rank}`}><b>{medals[index]}</b><strong>{row.displayName}</strong><span>+{row.points}</span><small>{(row.responseTimeMs/1000).toFixed(2)} s</small></li>)}</ol>:<p className="quiz-waiting">No correct responses were submitted.</p>}</section>}
  if(view==='final-podium'){const rows=(session?.leaderboard||[]).slice(0,3);return <section className="live-quiz-sequence final-podium-view" aria-live="polite"><p className="quiz-kicker">Total scores</p><h2>Today’s Top 3</h2>{rows.length?<div className="final-podium">{rows.map((row,index)=><article className={`podium-${index+1}`} key={`${row.displayName}-${index}`}><b>{medals[index]}</b><strong>{row.displayName}</strong><span>{row.score} points</span></article>)}</div>:<p className="quiz-waiting">The podium will appear after students earn points.</p>}</section>}
  const solution=slide.quizSolution||question?.solution
  return <section className="live-quiz-sequence solution-view"><div><p className="quiz-kicker">Correct answer</p><h2>{solution?.correctAnswer||question?.choices?.find(choice=>choice.id===question.correctChoiceId)?.text||question?.options?.[question?.correctAnswer]}</h2>{(solution?.steps||[]).map((step,index)=><MathDisplay key={index}>{step}</MathDisplay>)}{solution?.explanation&&<p>{solution.explanation}</p>}</div>{solution?.visual==='right-angle-vectors'&&<RightAngleVectors/>}{solution?.visual==='determinant-diagonals'&&<DeterminantDiagonals/>}</section>
}
