import { useState } from 'react'
import { MathDisplay } from '../../components/MathDisplay'
import { closeLectureQuestion, getNonResponders, getParticipationStats, getTopicAccuracy, reopenLectureQuestion, revealLectureAnswer, showLectureResults } from '../services/lectureSessionService'

function ResponseDashboard({session,question}){
  const [showResults,setShowResults]=useState(false),[revealAnswer,setRevealAnswer]=useState(false)
  if(!session)return <div className="response-dashboard"><strong>Private live-class dashboard</strong><p>Start a live lecture and ask a class question to collect responses.</p></div>
  const active=session.active_question||question,options=active?.options||[]
  const responses=(session.responses||[]).filter((r)=>r.question_id===active?.id)
  const eligible=active?.eligible_participant_ids?.length??session.participants.length,responded=new Set(responses.map((r)=>r.participant_id)).size
  const distribution=options.map((_,i)=>responses.filter((r)=>Number(r.answer)===i).length),correct=responses.filter((r)=>r.correct).length
  const nonResponders=getNonResponders(session),participation=getParticipationStats(session).sort((a,b)=>b.participation-a.participation),topics=getTopicAccuracy(session)
  return <div className="response-dashboard"><strong>Private live-class dashboard</strong><p className="question-status">Question status: <b>{session.question_status||'ready'}</b></p><dl><div><dt>Students connected</dt><dd>{session.participants.length}</dd></div><div><dt>Students responded</dt><dd>{responded}</dd></div><div><dt>Not responded</dt><dd>{nonResponders.length}</dd></div><div><dt>Response rate</dt><dd>{eligible?Math.round(responded/eligible*100):0}%</dd></div><div><dt>Class accuracy</dt><dd>{responses.length?Math.round(correct/responses.length*100):0}%</dd></div></dl><div className="response-controls"><button onClick={()=>closeLectureQuestion(session.id)}>Close</button><button onClick={()=>{showLectureResults(session.id);setShowResults(true)}}>Show Results</button><button onClick={()=>{revealLectureAnswer(session.id);setRevealAnswer(true)}}>Reveal Answer</button><button onClick={()=>reopenLectureQuestion(session.id)}>Reopen</button></div>{showResults&&<div className="answer-distribution">{options.map((option,i)=><div key={option}><span>{String.fromCharCode(65+i)} · {option}</span><progress max={Math.max(1,responses.length)} value={distribution[i]}/><strong>{responses.length?Math.round(distribution[i]/responses.length*100):0}%</strong>{revealAnswer&&i===(active.correctAnswer??active.correct_option_index)&&<b>Correct</b>}</div>)}</div>}<details open><summary>Not yet responded ({nonResponders.length})</summary>{nonResponders.length?<ul>{nonResponders.map((p)=><li key={p.id}>{p.name||`Student ${p.id}`}</li>)}</ul>:<p>Everyone eligible has responded.</p>}</details><details><summary>Private individual responses</summary>{session.participants.map((p)=>{const r=responses.find((item)=>item.participant_id===p.id);return <div className="individual-response" key={p.id}><span>{p.name||`Student ${p.id}`}</span><span>{r?(options[Number(r.answer)]??String(r.answer)):'—'}</span><b>{r?(r.correct?'Correct':'Incorrect'):'No response'}</b><small>{r?`${Math.round(r.response_time_ms/1000)}s`:'—'}</small></div>})}</details><details><summary>Participation / most active</summary>{participation.map((row)=><div className="participation-row" key={row.participant.id}><span>{row.participant.name}</span><span>{row.answered}/{row.available} answered</span><b>{row.participation}% participation</b><small>{row.accuracy}% accuracy</small></div>)}</details><details><summary>Understanding by topic</summary>{topics.map((topic)=><div className="topic-row" key={topic.topic}><span>{topic.topic}</span><b>{topic.accuracy}%</b><small>{topic.total} responses</small></div>)}</details></div>
}

export default function PresenterNotesPanel({notes=[],studentNotes=[],tab,onTabChange,session,question}){
  const blocks=tab==='student'?studentNotes:notes
  return <aside className="presenter-notes"><div className="notes-tabs"><button className={tab==='presenter'?'active':''} onClick={()=>onTabChange('presenter')}>Presenter Notes</button><button className={tab==='student'?'active':''} onClick={()=>onTabChange('student')}>Student Notes</button><button className={tab==='responses'?'active':''} onClick={()=>onTabChange('responses')}>Live Class</button></div>{tab==='responses'?<ResponseDashboard session={session} question={question}/>:<div className="notes-blocks">{blocks.length?blocks.map((block,index)=><section className={`note-block note-${block.type}`} key={`${block.title}-${index}`}><span>{block.type.replace('-',' ')}</span><h3>{block.title}</h3>{block.math&&<MathDisplay>{block.math}</MathDisplay>}<p>{block.content}</p></section>):<div className="notes-empty">No {tab} notes for this slide.</div>}</div>}</aside>
}
