import { useMemo, useState } from 'react'
import { MathInline } from '../../components/MathDisplay'
import './six-trig-inverse-master.css'

const PI=Math.PI
const rows=[
  {key:'sin',label:'sin → arcsin',fn:Math.sin,inv:Math.asin,originalDomain:'(-\\infty,\\infty)',originalRange:'[-1,1]',restricted:'[-\\pi/2,\\pi/2]',inverseDomain:'[-1,1]',principal:'[-\\pi/2,\\pi/2]',limits:[-PI/2,PI/2],invLimits:[-1,1],benchmark:'\\arcsin(1/2)=\\pi/6',point:[.5,PI/6]},
  {key:'cos',label:'cos → arccos',fn:Math.cos,inv:Math.acos,originalDomain:'(-\\infty,\\infty)',originalRange:'[-1,1]',restricted:'[0,\\pi]',inverseDomain:'[-1,1]',principal:'[0,\\pi]',limits:[0,PI],invLimits:[-1,1],benchmark:'\\arccos(-1/2)=2\\pi/3',point:[-.5,2*PI/3]},
  {key:'tan',label:'tan → arctan',fn:Math.tan,inv:Math.atan,originalDomain:'x\\ne\\pi/2+k\\pi',originalRange:'(-\\infty,\\infty)',restricted:'(-\\pi/2,\\pi/2)',inverseDomain:'(-\\infty,\\infty)',principal:'(-\\pi/2,\\pi/2)',limits:[-PI/2,PI/2],invLimits:[-3,3],benchmark:'\\arctan(1)=\\pi/4',point:[1,PI/4]},
  {key:'csc',label:'csc → arccsc',fn:x=>1/Math.sin(x),inv:x=>Math.asin(1/x),originalDomain:'x\\ne k\\pi',originalRange:'(-\\infty,-1]\\cup[1,\\infty)',restricted:'[-\\pi/2,\\pi/2]\\setminus\\{0\\}',inverseDomain:'(-\\infty,-1]\\cup[1,\\infty)',principal:'[-\\pi/2,\\pi/2]\\setminus\\{0\\}',limits:[-PI/2,PI/2],invLimits:[-3,3],benchmark:'\\operatorname{arccsc}(2)=\\pi/6',point:[2,PI/6]},
  {key:'sec',label:'sec → arcsec',fn:x=>1/Math.cos(x),inv:x=>Math.acos(1/x),originalDomain:'x\\ne\\pi/2+k\\pi',originalRange:'(-\\infty,-1]\\cup[1,\\infty)',restricted:'[0,\\pi]\\setminus\\{\\pi/2\\}',inverseDomain:'(-\\infty,-1]\\cup[1,\\infty)',principal:'[0,\\pi]\\setminus\\{\\pi/2\\}',limits:[0,PI],invLimits:[-3,3],benchmark:'\\operatorname{arcsec}(2)=\\pi/3',point:[2,PI/3]},
  {key:'cot',label:'cot → arccot',fn:x=>1/Math.tan(x),inv:x=>Math.atan2(1,x),originalDomain:'x\\ne k\\pi',originalRange:'(-\\infty,\\infty)',restricted:'(0,\\pi)',inverseDomain:'(-\\infty,\\infty)',principal:'(0,\\pi)',limits:[0,PI],invLimits:[-3,3],benchmark:'\\operatorname{arccot}(1)=\\pi/4',point:[1,PI/4]},
]

const W=560,H=330,p={l:42,r:16,t:18,b:34},xMin=-PI,xMax=PI,yMin=-3.25,yMax=3.25
const X=x=>p.l+(x-xMin)/(xMax-xMin)*(W-p.l-p.r),Y=y=>p.t+(yMax-y)/(yMax-yMin)*(H-p.t-p.b)
function makeSegments(fn,min,max){const segments=[];let points=[];for(let i=0;i<=600;i++){const x=min+(max-min)*i/600,y=fn(x),valid=Number.isFinite(y)&&y>=yMin&&y<=yMax;if(!valid){if(points.length>1)segments.push(points);points=[]}else points.push(`${X(x).toFixed(1)},${Y(y).toFixed(1)}`)}if(points.length>1)segments.push(points);return segments}

export default function SixTrigInverseMaster(){
  const [selected,setSelected]=useState('sin'),[mode,setMode]=useState('original'),row=rows.find(item=>item.key===selected)
  const graph=useMemo(()=>{const inverse=mode==='inverse',domain=inverse?row.invLimits:mode==='restricted'?row.limits:[-PI,PI];return{segments:makeSegments(inverse?row.inv:row.fn,domain[0]+(mode==='restricted'?1e-3:0),domain[1]-(mode==='restricted'?1e-3:0)),domain,inverse}},[mode,row])
  const shadeStart=X(Math.max(xMin,graph.domain[0])),shadeEnd=X(Math.min(xMax,graph.domain[1])),benchmark=mode==='inverse'?row.point:[row.point[1],row.point[0]]
  return <section className="six-trig-master"><header><div><strong>6-Trig & Inverse Master Visual</strong><span>{row.label}</span></div><div role="group" aria-label="Graph mode">{['original','restricted','inverse'].map(value=><button className={mode===value?'active':''} onClick={()=>setMode(value)} key={value}>{value}</button>)}</div></header><div className="six-trig-master-grid"><section className="six-trig-graph"><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label={`${mode} graph for ${row.label}`}><rect className="domain-shade" x={shadeStart} y={p.t} width={Math.max(0,shadeEnd-shadeStart)} height={H-p.t-p.b}/><line className="master-axis" x1={p.l} x2={W-p.r} y1={Y(0)} y2={Y(0)}/><line className="master-axis" x1={X(0)} x2={X(0)} y1={p.t} y2={H-p.b}/>{[-1,-.5,0,.5,1].map(value=><g key={value}><line className="master-tick" x1={X(value*PI)} x2={X(value*PI)} y1={Y(0)-4} y2={Y(0)+4}/><text x={X(value*PI)} y={H-10} textAnchor="middle">{{'-1':'−π','-0.5':'−π/2','0':'0','0.5':'π/2','1':'π'}[String(value)]}</text></g>)}{graph.segments.map((points,index)=><polyline className="master-curve" points={points.join(' ')} key={index}/>)}{benchmark[0]>=xMin&&benchmark[0]<=xMax&&benchmark[1]>=yMin&&benchmark[1]<=yMax&&<><line className="benchmark-guide" x1={X(benchmark[0])} x2={X(benchmark[0])} y1={Y(0)} y2={Y(benchmark[1])}/><circle className="master-benchmark" cx={X(benchmark[0])} cy={Y(benchmark[1])} r="7"/></>}<line className="endpoint" x1={shadeStart} x2={shadeStart} y1={p.t} y2={H-p.b}/><line className="endpoint" x1={shadeEnd} x2={shadeEnd} y1={p.t} y2={H-p.b}/></svg><footer><span>Shaded interval: <MathInline>{mode==='inverse'?row.inverseDomain:mode==='restricted'?row.restricted:'[-\\pi,\\pi]\\text{ viewing window}'}</MathInline></span><strong><MathInline>{row.benchmark}</MathInline></strong></footer></section><section className="six-trig-table" role="table" aria-label="Master domain and range table"><div className="master-table-head" role="row"><b>Function</b><b>Original D / R</b><b>Restricted</b><b>Inverse D / principal R</b><b>Benchmark</b></div>{rows.map(item=><button className={selected===item.key?'active':''} onClick={()=>setSelected(item.key)} role="row" key={item.key}><strong>{item.label}</strong><span><MathInline>{item.originalDomain}</MathInline><br/><MathInline>{item.originalRange}</MathInline></span><span><MathInline>{item.restricted}</MathInline></span><span><MathInline>{item.inverseDomain}</MathInline><br/><MathInline>{item.principal}</MathInline></span><span><MathInline>{item.benchmark}</MathInline></span></button>)}</section></div></section>
}
