const courseModules = [
  {
    number: '01',
    chapterLabel: 'CHAPTER 7',
    title: 'Integration Techniques',
    summary: 'Learn to recognize an integrand\'s structure and select an efficient method.',
    topics: [
      'Integration by parts and where its formula comes from',
      'Trigonometric integrals and trigonometric substitution',
      'Partial fractions, radicals, and quadratic expressions',
      'Improper integrals, comparison, and convergence decisions',
      'Numerical approximation when an antiderivative is unavailable',
    ],
    habit: 'Before calculating, name the feature of the integrand that suggests your method.',
  },
  {
    number: '02',
    chapterLabel: 'CHAPTER 8',
    title: 'Applications of Integrals',
    summary: 'Turn a physical or geometric situation into a definite integral.',
    topics: [
      'Arc length and surfaces generated by rotation',
      'Centroids and centers of mass for planar regions',
      'Hydrostatic pressure and force on submerged plates',
      'Average values arising from probability density functions',
    ],
    habit: 'Define a representative slice, include its units, and identify what is being accumulated.',
  },
  {
    number: '03',
    chapterLabel: 'CHAPTER 9',
    title: 'Parametric & Polar Calculus',
    summary: 'Describe curves that are awkward or impossible to express as one Cartesian function.',
    topics: [
      'Parametric curves, orientation, and eliminating a parameter',
      'Parametric slopes, concavity, area, arc length, and surface area',
      'Polar coordinates, conversions, and families of polar graphs',
      'Polar tangents, enclosed area, arc length, and surface area',
    ],
    habit: 'Keep track of how the parameter or angle moves; direction is part of the curve.',
  },
  {
    number: '04',
    title: 'Sequences & Series',
    summary: 'Decide whether infinite processes settle, and represent functions by infinite sums.',
    topics: [
      'Sequence limits, monotonicity, and boundedness',
      'Partial sums and geometric, telescoping, and harmonic series',
      'Integral, comparison, alternating, ratio, and root tests',
      'Absolute versus conditional convergence and error estimates',
      'Power-series operations; Taylor, Maclaurin, binomial, and function approximations',
    ],
    habit: 'Check a test\'s hypotheses before using its conclusion, and state what the result proves.',
  },
  {
    number: '05',
    chapterLabel: 'CHAPTER 12',
    title: 'VECTORS & 3D SPACE',
    summary: 'Build the geometric language that connects Calculus II with multivariable calculus.',
    topics: [
      'Vector notation, magnitude, arithmetic, and unit vectors',
      'Dot products, projections, cross products, and geometric meaning',
      'Coordinates, lines, planes, and quadric surfaces in space',
      'Functions of several variables, domains, level sets, and traces',
      'Limits, derivatives, integrals, and tangent, normal, and binormal frames for vector functions',
      'Vector-valued motion, arc length, curvature, velocity, and acceleration',
      'Cylindrical and spherical coordinate systems',
    ],
    habit: 'Translate between an equation, a geometric object, and a visual model whenever possible.',
  },
]

export default function Calculus2CourseRoadmap() {
  return (
    <section className="calc2-orientation" aria-labelledby="calc2-orientation-heading">
      <div className="calc2-orientation-heading">
        <div>
          <span className="card-label">Course orientation</span>
          <h2 id="calc2-orientation-heading">How to learn Calculus II</h2>
        </div>
        <p>
          Success comes from combining reliable Calculus I skills with good mathematical judgment.
          The central question is often not “Which formula do I remember?” but “Which method fits,
          and why?”
        </p>
      </div>

      <div className="calc2-readiness-grid">
        <article>
          <span className="calc2-orientation-number" aria-hidden="true">01</span>
          <div>
            <h3>Keep the foundation active</h3>
            <p>
              Algebra, trigonometry, limits, derivatives, basic antiderivatives, and substitution
              remain part of nearly every new topic. Worked examples may compress these familiar
              steps, so use the reviews below whenever one of them slows you down.
            </p>
          </div>
        </article>
        <article>
          <span className="calc2-orientation-number" aria-hidden="true">02</span>
          <div>
            <h3>Choose before you compute</h3>
            <p>
              Many problems allow more than one approach. Read the structure, list plausible
              methods, verify that their conditions apply, and then choose the clearest route.
              If the algebra grows worse, pause and reconsider the strategy.
            </p>
          </div>
        </article>
      </div>

      <div className="calc2-learning-sequence" aria-label="Learning sequence used in the review exercises">
        <div>
          <span>1</span>
          <strong>Orient</strong>
          <p>See the purpose and recognize the pattern.</p>
        </div>
        <i aria-hidden="true">→</i>
        <div>
          <span>2</span>
          <strong>Define</strong>
          <p>State the idea, rule, and conditions precisely.</p>
        </div>
        <i aria-hidden="true">→</i>
        <div>
          <span>3</span>
          <strong>Practice</strong>
          <p>Apply it to an exercise and explain the choice.</p>
        </div>
      </div>

      <aside className="calc2-class-note" aria-labelledby="calc2-class-note-heading">
        <span aria-hidden="true">i</span>
        <div>
          <h3 id="calc2-class-note-heading">Use this resource alongside the classroom</h3>
          <p>
            These materials provide definitions, guided examples, and extra practice. A live class
            may emphasize different examples, omit an extension, or develop an unexpected insight
            from student questions. If you miss a meeting, compare this resource with a classmate’s
            notes and check with your professor; the application supports the course but does not
            replace participation.
          </p>
        </div>
      </aside>

      <div className="calc2-roadmap-heading">
        <div>
          <span className="card-label">Course roadmap</span>
          <h3>What you will learn</h3>
        </div>
        <p>Select a pathway to preview its major ideas and the thinking habit that connects them.</p>
      </div>

      <div className="calc2-roadmap-accordion">
        {courseModules.map((module) => (
          <details key={module.number}>
            <summary>
              <span className="calc2-module-number" aria-hidden="true">{module.number}</span>
              <span className="calc2-module-title">
                <strong>{module.chapterLabel || module.title}</strong>
                {module.chapterLabel && <span>{module.title}</span>}
                <small>{module.summary}</small>
              </span>
              <span className="calc2-module-toggle" aria-hidden="true">+</span>
            </summary>
            <div className="calc2-module-content">
              <ul>
                {module.topics.map((topic) => <li key={topic}>{topic}</li>)}
              </ul>
              <p><strong>Strategic habit:</strong> {module.habit}</p>
            </div>
          </details>
        ))}
      </div>
    </section>
  )
}
