import { useEffect, useMemo, useState } from 'react'
import { MathDisplay } from '../../components/MathDisplay'
import HyperbolicStoryVisuals from '../../instructor/components/HyperbolicStoryVisuals'
import './hyperbolic-study.css'

const sections=[
  {id:'origin',title:'Where the functions come from',stage:'reflection',formula:String.raw`e^x\longrightarrow e^{-x}`,intuition:'Replacing x by −x mirrors the exponential graph across the y-axis. The exponential is neither even nor odd, but it contains both symmetries.',why:'A horizontal reflection changes the input sign. Exponential outputs stay positive.',previous:'Graph transformations and f(−x).'},
  {id:'parity',title:'Even and odd components',stage:'decomposition',formula:String.raw`E(x)=\frac{f(x)+f(-x)}2,\qquad O(x)=\frac{f(x)-f(-x)}2`,intuition:'Average a graph with its mirror to keep only y-axis symmetry. Take half their difference to keep only origin symmetry.',why:'Addition cancels opposite odd values and doubles the even part; subtraction cancels the even part and doubles the odd part.',previous:'Even/odd functions and elimination of simultaneous equations.'},
  {id:'definitions',title:'Discover sinh and cosh',stage:'reconstruct',formula:String.raw`\cosh x=\frac{e^x+e^{-x}}2,\qquad\sinh x=\frac{e^x-e^{-x}}2`,intuition:'Cosh is the even part of eˣ. Sinh is the odd part. Their sum reconstructs eˣ and their difference reconstructs e⁻ˣ.',why:'These formulas are the universal even/odd decomposition applied to f(x)=eˣ.',previous:'Exponentials, averages, and symmetry.'},
  {id:'series',title:'Taylor series sees the same split',stage:'series',formula:String.raw`\cosh x=\sum_{n=0}^\infty\frac{x^{2n}}{(2n)!},\qquad\sinh x=\sum_{n=0}^\infty\frac{x^{2n+1}}{(2n+1)!}`,intuition:'Even powers do not change under x→−x; odd powers reverse sign.',why:'Separating the Taylor series for eˣ by exponent parity produces exactly cosh and sinh.',previous:'Taylor series and powers of negative numbers.'},
  {id:'geometry',title:'Circle versus hyperbola',stage:'circle-hyperbola',formula:String.raw`(\cos\theta,\sin\theta)\leftrightarrow x^2+y^2=1,\qquad(\cosh A,\sinh A)\leftrightarrow x^2-y^2=1`,intuition:'Hyperbolic functions parameterize the right branch of the unit hyperbola in a structure analogous to circular trigonometry.',why:'Substitution of x=cosh A and y=sinh A gives cosh²A−sinh²A=1.',previous:'Unit-circle coordinates and parametric curves.'},
  {id:'sector',title:'The hyperbolic parameter',stage:'sector',formula:String.raw`A=2(\text{signed hyperbolic sector area})`,intuition:'A is not an ordinary angle. It is an area-based parameter analogous to θ on the unit circle.',why:'For a unit circle, sector area is θ/2. The hyperbolic convention is chosen in exact analogy.',previous:'Radian measure and unit-circle sector area.'},
  {id:'identity',title:'Fundamental identity',stage:'identity',formula:String.raw`\cosh^2x-\sinh^2x=1`,intuition:'The minus sign matches the hyperbola equation and forces the exponential cross terms to cancel.',why:'Expand the exponential definitions; e²ˣ and e⁻²ˣ cancel, leaving 4/4.',previous:'Difference of squares and the Pythagorean identity.'},
  {id:'graphs',title:'Graphs and the catenary',stage:'graphs',formula:String.raw`\cosh0=1,\quad\sinh0=0,\quad y=a\cosh(x/a)`,intuition:'Cosh is even and never below 1. Sinh is odd. A freely hanging uniform chain forms a catenary, not a parabola.',why:'The exponential definitions determine symmetry, intercepts, and end behavior.',previous:'Graph symmetry, transformations, and exponential growth.'},
  {id:'calculus',title:'Derivatives and integrals',stage:'derivatives',formula:String.raw`(\sinh x)'=\cosh x,\quad(\cosh x)'=\sinh x,\quad\int\cosh x\,dx=\sinh x+C`,intuition:'Differentiation swaps sinh and cosh. Unlike the circular cycle, no negative sign appears.',why:'The chain-rule negative from differentiating e⁻ˣ combines with the sign already in each definition.',previous:'Exponential derivatives, the Chain Rule, and antiderivatives.'},
  {id:'family',title:'The rest of the family',stage:'graphs',formula:String.raw`\tanh x=\frac{\sinh x}{\cosh x},\quad\operatorname{sech}x=\frac1{\cosh x},\quad\coth x=\frac{\cosh x}{\sinh x},\quad\operatorname{csch}x=\frac1{\sinh x}`,intuition:'The other four functions are ratios and reciprocals, introduced only after sinh and cosh are understood.',why:'Their definitions mirror the organization of ordinary trigonometric ratios.',previous:'Tangent, cotangent, secant, and cosecant.'},
  {id:'inverse',title:'Inverse hyperbolic functions',stage:'concept-map',formula:String.raw`\operatorname{arsinh}x=\ln(x+\sqrt{x^2+1})`,intuition:'Sinh is one-to-one. Cosh must be restricted to x≥0 before inversion.',why:'Solving x=(eʸ−e⁻ʸ)/2 as a quadratic in eʸ produces the logarithmic form.',previous:'Inverse functions, logarithms, and domain restriction.'},
]

const examples=[
 ['Evaluate',String.raw`\cosh(\ln2)`,String.raw`\frac{2+1/2}{2}=\frac54`,'Replace e^{ln 2} by 2 and e^{-ln 2} by 1/2.'],
 ['Prove an identity',String.raw`\cosh(2x)=\cosh^2x+\sinh^2x`,String.raw`\frac{e^{2x}+e^{-2x}}2=\left(\frac{e^x+e^{-x}}2\right)^2+\left(\frac{e^x-e^{-x}}2\right)^2`,'Expand both sides from definitions.'],
 ['Differentiate',String.raw`y=\sinh(3x^2)`,String.raw`y'=6x\cosh(3x^2)`,'Use the Chain Rule; keep the inner expression unchanged.'],
 ['Integrate',String.raw`\int 4\cosh(2x)\,dx`,String.raw`2\sinh(2x)+C`,'Differentiate the answer: the inner derivative 2 restores the coefficient 4.'],
 ['Simplify',String.raw`\frac{1-\tanh^2x}{\operatorname{sech}^2x}`,String.raw`1`,'Divide cosh²−sinh²=1 by cosh².'],
 ['Catenary slope',String.raw`y=a\cosh(x/a)`,String.raw`y'=\sinh(x/a)`,'The outer factor a cancels the 1/a from the Chain Rule.'],
 ['Inverse connection',String.raw`y=\operatorname{arsinh}x`,String.raw`y'=\frac1{\sqrt{x^2+1}}`,'Differentiate sinh y=x implicitly and use cosh²y=1+sinh²y.'],
]

const modes=['Explain simply','Explain visually','Show the algebra','Connect to previous material','Give me an example','Give me a hint','Quiz me','Why is this true?']
function Tutor({context}){
  const [open,setOpen]=useState(false),[mode,setMode]=useState(modes[0]),[attempt,setAttempt]=useState(0),[question,setQuestion]=useState(''),[animation,setAnimation]=useState({stage:context.stage,step:0,value:1})
  useEffect(()=>{const update=event=>{if(event.detail?.stage===context.stage)setAnimation(event.detail)};window.addEventListener('hyperbolic-animation-context',update);return()=>window.removeEventListener('hyperbolic-animation-context',update)},[context.stage])
  const response=useMemo(()=>{const n=attempt%5,q=question.toLowerCase();if(q.includes('flip')||q.includes('below'))return 'The minus sign is inside the exponent, so it changes the input: e⁻ˣ is the y-axis reflection of eˣ. It does not negate the output; −eˣ would lie below the x-axis.';if(q.includes('divide')||q.includes('denominator'))return 'Adding f(x) and f(−x) cancels the odd part but produces two copies of the even part. Dividing by 2 leaves one copy—this is an average.';if(q.includes('even'))return 'Cosh is even because x→−x merely swaps eˣ and e⁻ˣ inside a sum, leaving the value unchanged.';if(q.includes('odd')||q.includes('subtract'))return 'Sinh is odd because x→−x reverses the subtraction order, multiplying the result by −1.';if(mode==='Show the algebra'||mode==='Why is this true?')return context.why;if(mode==='Connect to previous material')return `Connect this to ${context.previous} ${context.why}`;if(mode==='Explain visually')return `Watch the ${context.stage} visualization one step at a time. Track what changes and what remains invariant. ${context.intuition}`;if(mode==='Give me an example')return context.id==='definitions'?'At x=0: e⁰=e⁻⁰=1, so cosh 0=(1+1)/2=1 and sinh 0=(1−1)/2=0.':`Try x=0 or x=1 in the displayed formula, then compare the result with the graph.`;if(mode==='Give me a hint')return `Start from: ${context.intuition.split('.')[0]}. Do one substitution before revealing another step.`;if(mode==='Quiz me')return 'Without looking: explain why the displayed formula has its current plus or minus sign.';return [context.intuition,`Forget the symbols briefly: imagine the original exponential and its mirror. Combining their heights isolates symmetry. ${context.intuition}`,'Use a number: choose x=1 and compare both sides numerically. Then return to the formula.',context.why,'Guided question: which term changes sign when x becomes −x?'][n]},[attempt,context,mode,question])
  return <aside className="hy-ai-tutor"><button className="hy-ai-open" onClick={()=>setOpen(value=>!value)}>Ask AI about this</button>{open&&<div><header><strong>Context Tutor</strong><small>{context.title} · animation: {animation.stage} · step {animation.step} · value {Number(animation.value).toFixed(2)}</small></header><div className="hy-ai-modes">{modes.map(item=><button className={mode===item?'active':''} onClick={()=>{setMode(item);setAttempt(0)}} key={item}>{item}</button>)}</div><label>Your question<textarea value={question} onChange={event=>setQuestion(event.target.value)} placeholder="Why did the graph flip? Why divide by 2?"/></label><p>{response}</p><button onClick={()=>setAttempt(value=>value+1)}>I still don’t understand</button><small>When you ask again, the tutor changes representation instead of repeating the same explanation.</small></div>}</aside>
}

export default function HyperbolicStudyLecture({completed={},onCompletedChange,onOverview,onHome}){
  const [active,setActive]=useState(0),[example,setExample]=useState(null),section=sections[active]
  return <main className="hyperbolic-study"><nav><button onClick={onOverview}>← Trigonometry</button><button onClick={onHome}>Home</button></nav><header><p>Complete self-study lecture · Calculus II</p><h1>Hyperbolic Functions</h1><span>Exponential symmetry → Taylor series → unit hyperbola → calculus</span></header><div className="hy-study-layout"><aside className="hy-study-nav">{sections.map((item,index)=><button className={active===index?'active':''} onClick={()=>{setActive(index);setExample(null)}} key={item.id}><span>{String(index+1).padStart(2,'0')}</span>{item.title}{completed[`hyperbolic-${item.id}`]&&<b>✓</b>}</button>)}</aside><article className="hy-study-content"><p className="hy-study-label">{active+1} · {section.title}</p><h2>{section.title}</h2><section><h3>Intuition</h3><p>{section.intuition}</p></section><MathDisplay>{section.formula}</MathDisplay><HyperbolicStoryVisuals stage={section.stage}/><details><summary>Why does this work?</summary><p>{section.why}</p></details><details><summary>Connection to what you already know</summary><p>{section.previous}</p></details><Tutor context={section}/><button className="hy-complete" onClick={()=>onCompletedChange?.({...completed,[`hyperbolic-${section.id}`]:true})}>Mark this section understood</button></article></div><section className="hy-examples"><header><p>Understand · Plan · Execute · Why · Check · Common Mistake</p><h2>Complete worked examples</h2></header>{examples.map((item,index)=><article key={item[0]}><span>Example {index+1}</span><h3>{item[0]}</h3><MathDisplay>{item[1]}</MathDisplay><button onClick={()=>setExample(example===index?null:index)}>{example===index?'Hide solution':'Reveal solution'}</button>{example===index&&<div><strong>Understand / Plan</strong><p>{item[3]}</p><strong>Execute / Answer</strong><MathDisplay>{item[2]}</MathDisplay><strong>Check</strong><p>Differentiate, substitute, or compare with symmetry and graph behavior.</p><strong>Common mistake</strong><p>Watch the sign on e⁻ˣ and include every Chain Rule factor.</p></div>}</article>)}</section><section className="hy-study-summary"><HyperbolicStoryVisuals stage="concept-map"/><h2>Mastery check</h2><ul><li>I can derive sinh and cosh from even/odd decomposition.</li><li>I can explain the factor 1/2.</li><li>I can connect the identity to the unit hyperbola.</li><li>I can derive derivatives and solve representative examples.</li></ul></section></main>
}
